image: radupopescu/erlang-libsodium:19

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  tags:
    - docker
  script: rebar3 release

dialyzer:
  stage: test
  tags:
    - docker
  script: rebar3 dialyzer

common_test:
  stage: test
  tags:
    - docker
  script: rebar3 ct

release:
  stage: deploy
  tags:
    - docker
  script: rebar3 as prod tar
