image: radupopescu/erlang-libsodium:19

stages:
  - build

dialyzer:
  stage: build
  tags:
    - docker
  script: rebar3 dialyzer

common_test:
  stage: build
  tags:
    - docker
  script: rebar3 ct
