language: erlang

otp_release:
  - 19.0

notifications:
  email:
    recipients:
      - mail@radupopescu.net
    on_success: change
    on_failure: always

before_script:
  - wget -O ~/rebar3 https://s3.amazonaws.com/rebar3/rebar3 && chmod +x ~/rebar3

script:
  - ~/rebar3 compile
