language: erlang

otp_release:
  - 19.0

notifications:
  email:
    recipients:
      - mail@radupopescu.net
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.cache/rebar3
    - $HOME/bin

before_script:
  - ./ci/travis_before.sh

script:
  - ./ci/travis_main.sh
